# Generated by Django 5.0 on 2024-04-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='accepted_at',
            field=models.DateField(null=True),
        ),
    ]
