# Generated by Django 5.0 on 2024-04-12 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 12, 20, 48, 16, 629367), null=True),
        ),
    ]
