# Generated by Django 5.0 on 2024-04-06 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gighire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gigproposal',
            name='requestdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
