# Generated by Django 5.0 on 2024-04-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gighire', '0002_gigproposal_requestdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigproposal',
            name='acceptedate',
            field=models.DateField(null=True),
        ),
    ]
