# Generated by Django 5.0 on 2024-04-06 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gighire', '0003_alter_gigproposal_acceptedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gigproposal',
            name='paymethod',
            field=models.DateField(null=True),
        ),
    ]
