# Generated by Django 5.0 on 2024-04-08 17:35

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gighire', '0005_alter_gigproposal_paymethod'),
        ('jobposting', '0001_initial'),
        ('registration', '0002_rename_expired_at_verificationcode_expired'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField()),
                ('reportdate', models.DateField(default=datetime.date.today)),
                ('gigproposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gig_Proposalworkreport', to='gighire.gigproposal')),
                ('jobproposal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_workreportworkreport', to='jobposting.jobrequirement')),
                ('reporteduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userreportedworkreport', to='registration.user')),
                ('reportuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userreportwork', to='registration.user')),
            ],
        ),
    ]
