# Generated by Django 5.0 on 2024-04-05 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(null=True, upload_to='image/brand')),
            ],
        ),
        migrations.CreateModel(
            name='BrandItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(null=True, upload_to='image/branditem')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branditem', to='brand.brand')),
            ],
        ),
    ]
