# Generated by Django 5.0 on 2024-04-13 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='image',
        ),
    ]
