# Generated by Django 5.0 on 2024-04-05 15:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('budget', models.IntegerField()),
                ('isFeatured', models.BooleanField(default=False)),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('location', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='image/jobreq')),
                ('jobStatus', models.CharField(default='inprogress', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobreqcategory', to='category.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobrequser', to='registration.user')),
            ],
        ),
    ]
