# Generated by Django 5.0 on 2024-04-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verificationcode',
            old_name='expired_at',
            new_name='expired',
        ),
    ]
